language: java
jdk:
  - oraclejdk8
services:
  - mysql
sudo: true
cache:
  directories:
  - $HOME/.m2

before_script:
#  - bash .travis/travis-install-mysql-5.7.sh
  - mysql -e 'DROP DATABASE IF EXISTS geronimo_test;'
  - mysql -e 'CREATE DATABASE geronimo_test;'

script: ./mvnw test -B -Dmaven.javadoc.skip=true -Dspring.profiles.active=travis-ci

install: true
