language: java
jdk:
  - oraclejdk8
script: ./mvnw test -B -Dmaven.javadoc.skip=true -Dspring.profiles.active=travis-ci
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS geronimo_test;'
install: true