language: java
sudo: required
services:
  - docker
env:
  - DOCKER_COMPOSE_VERSION=1.16.1

cache:
  bundler: true
  directories:
    - $HOME/.docker

before_cache:
  # Save tagged docker images
  - >
    mkdir -p $HOME/.docker && docker images -a --filter='dangling=false' --format '{{.Repository}}:{{.Tag}} {{.ID}}'
    | xargs -n 2 -t sh -c 'test -e $HOME/.docker/$1.tar.gz || docker save $0 | gzip -2 > $HOME/.docker/$1.tar.gz'

before_install:
  # update and install newest docker
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  # remove old docker-compose and download the newest docker-compose
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  # make docker-compose executable and move to a dir mapped into $PATH
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  # check version of docker-compose (will be visible in travis-ci log)
  - docker-compose --version
  # create network required to run docker-compose build
  - docker network create geronimo_network
  # load cached docker images
  - if [[ -d $HOME/.docker ]]; then ls $HOME/.docker/*.tar.gz | xargs -I {file} sh -c "zcat {file} | docker load"; fi

# skip the install step
install: true
# build and start the containers, run tests, install jar, and stop the containers
script:
  - docker-compose -f docker-compose-travis.yml build
  - docker-compose -f docker-compose-travis.yml up --timeout 1 --no-build -d
  - docker-compose -f docker-compose-travis.yml run webapp mvn clean flyway:migrate test -Pdocker
  - docker-compose -f docker-compose-travis.yml run webapp mvn clean install -DskipTests=true
  - docker-compose -f docker-compose-travis.yml stop

