language: java
jdk:
  - oraclejdk8
services:
  - mysql
sudo: true
cache:
  directories:
  - $HOME/.m2

before_script:
#  - bash .travis/travis-install-mysql-5.7.sh
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('5472') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
  - mysql -e 'DROP DATABASE IF EXISTS geronimo_test;'
  - mysql -e 'CREATE DATABASE geronimo_test;'

script: ./mvnw clean flyway:migrate test -P test
