language: java
jdk:
  - oraclejdk8
services:
  - mysql
sudo: true
cache:
  directories:
  - $HOME/.m2

before_script:
  - bash .travis/travis-install-mysql-5.7.sh
script: ./mvnw test -B -Dmaven.javadoc.skip=true -Dspring.profiles.active=travis-ci

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS geronimo_test;'
install: true
