version: '3.3'

services:
  mysqldb:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: geronimo_test
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: 5472
    networks:
      - geronimo_network

  webapp:
    build: .
    command:
      - /bin/sh
      - -c
      - |
          mvn clean flyway:migrate test -Pdocker
          mvn clean install
    environment:
      # these env variables are referenced in pom.xml
      MYSQL_HOST: mysqldb:3306
      MYSQL_USER: root
      MYSQL_PASSWORD: 5472
      MYSQL_DATABASE: geronimo_test
      MYSQL_ROOT_PASSWORD: 5472
    depends_on:
      - mysqldb
    networks:
      - geronimo_network

volumes:
  db_data:

networks:
  geronimo_network:
    external: true
