# pom.xml properties could be imported here, using special syntax @variable.name@

spring:
  # set active profile from maven properties (maybe there's a better way?)
  profiles.active: @spring.profiles.active@
  datasource:
    url: @db.url@
    username: @db.username@
    password: @db.password@
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: false
  thymeleaf:
    cache: true
    suffix: .html
    prefix: classpath:/templates/
    mode: HTML

---

spring:
  profiles: test
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/geronimo_test?useUnicode=yes&amp;characterEncoding=UTF-8
    username: root
    password: 5472

---

logging:
  file: @logging.file@
  path: @logging.path@
  config: classpath:logbackx.groovy
