# pom.xml properties could be imported here, using special syntax @variable.name@

spring:
  # set active profile from maven properties (maybe there's a better way?)
  profiles.active: @spring.profiles.active@
  datasource:
    url: @db.url@
    username: @db.username@
    password: @db.password@
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: false
  thymeleaf:
    cache: true
    suffix: .html
    prefix: classpath:/templates/
    mode: HTML

management:
  security:
    enabled: false


logging:
  file: @logging.file@
  path: @logging.path@
  config: classpath:logback-spring.groovy

---

spring:
  profiles: test
