# pom.xml properties could be imported here, using special syntax @variable.name@

spring:
  datasource:
    url: @db.url@
    username: @db.username@
    password: @db.password@
  jpa:
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: false
      show-sql: true
flyway:
  url: @db.url@
  user: @db.username@
  password: @db.password@
  locations: db/migrations/

---

spring:
  profiles: test
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/geronimo_test?useUnicode=yes&amp;characterEncoding=UTF-8

flyway:
  url: jdbc:mysql://localhost:3306/geronimo_test?useUnicode=yes&amp;characterEncoding=UTF-8

---

spring:
  profiles: travis-ci
flyway:
  url: jdbc:mysql://127.0.0.1:3306/geronimo_test?useUnicode=yes&amp;characterEncoding=UTF-8
  user: root
  password: ~

