# pom.xml properties could be imported here, using special syntax @variable.name@

spring:
  # set active profile from maven properties (maybe there's a better way?)
  profiles.active: @spring.profiles.active@
  datasource:
    url: @db.url@
    username: @db.username@
    password: @db.password@
  jpa:
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: false
      show-sql: true

---

spring:
  profiles: test
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/geronimo_test?useUnicode=yes&amp;characterEncoding=UTF-8
    username: root
    password: 5472

---

spring:
  profiles: travis-ci
  datasource:
      url: jdbc:mysql://127.0.0.1:3306/geronimo_test?useUnicode=yes&amp;characterEncoding=UTF-8
      username: root
      password: ~
